/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Epub {
  constructor(path: string)
  readFileNames(): Array<string>
  readFileContentByName(fileName: string): string
  writeFileContentByName(fileName: string, content: string): void
  exportFile(rawPath: string): void
  extract(): void
}
