/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsZip = Zip
export class Zip {
  constructor(path: string)
  readFileNames(): Array<string>
  readFileContentByName(fileName: string): string
  writeFileContentByName(fileName: string, content: string): void
  extract(path: string): void
}
